module.exports = {
  DONE: 'DONE',
  NO_RESULTS: 'NO_RESULTS',
  LOADING: 'LOADING',
  GEOLOCATION_SUCCESS: 'GEOLOCATION_SUCCESS',
  GEOLOCATION_FAIL: 'GEOLOCATION_FAIL',
  API_SUCCESS: 'API_SUCCESS',
  API_FAIL: 'API_FAIL'
};